language: ruby
cache:
  - bundler
install:
  - bundle install
rvm:
  - 1.9.3
  - 2.0
  - 2.1
notifications:
  irc:
    channels:
      - "chat.freenode.net#sensu"
    on_success: change
    on_failure: always
  email:
    recipients:
      - sensu-plugin@sensu-plugin.io
      - rich.m.chatterton@gmail.com
    on_success: change
    on_failure: always

script:
  - 'bundle exec rake default'
